name: Spring Boot + Vite React CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'

      - name: Build and test backend (Maven)
        run: mvn clean verify

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/main
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: npm install

      - name: Build React app (Vite)
        run: npm run build
